# Generated by Django 5.2.15 on 2026-06-18 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExposureMedia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("audio", "오디오"),
                            ("video", "비디오"),
                            ("image", "이미지"),
                        ],
                        max_length=10,
                        verbose_name="미디어 유형",
                    ),
                ),
                ("category", models.CharField(max_length=100, verbose_name="카테고리")),
                (
                    "intensity",
                    models.PositiveSmallIntegerField(verbose_name="강도(1~5)"),
                ),
                (
                    "asset_ref",
                    models.CharField(max_length=500, verbose_name="에셋 참조"),
                ),
            ],
            options={
                "verbose_name": "노출 자극 미디어",
                "verbose_name_plural": "노출 자극 미디어",
            },
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("erp_exposure", "ERP 노출"),
                            ("urge_surfing", "충동 파도타기"),
                        ],
                        max_length=20,
                        verbose_name="세션 유형",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="시작 시각"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="종료 시각"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="완료 여부"),
                ),
                (
                    "duration_sec",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="소요 시간(초)"
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="core.exposuremedia",
                        verbose_name="미디어",
                    ),
                ),
            ],
            options={
                "verbose_name": "훈련 세션",
                "verbose_name_plural": "훈련 세션",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="UrgeSurfingSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "peak_urge",
                    models.PositiveSmallIntegerField(verbose_name="최고 충동(0~10)"),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "성공"),
                            ("relapse", "재발"),
                            ("aborted", "중단"),
                        ],
                        max_length=10,
                        verbose_name="결과",
                    ),
                ),
                (
                    "coping_skill",
                    models.CharField(max_length=200, verbose_name="사용한 대처 기술"),
                ),
                (
                    "duration_sec",
                    models.PositiveIntegerField(verbose_name="소요 시간(초)"),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urge_surfing",
                        to="core.trainingsession",
                        verbose_name="세션",
                    ),
                ),
            ],
            options={
                "verbose_name": "충동 파도타기 세션",
                "verbose_name_plural": "충동 파도타기 세션",
            },
        ),
        migrations.CreateModel(
            name="VasRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[("pre", "사전"), ("post", "사후")],
                        max_length=4,
                        verbose_name="단계",
                    ),
                ),
                (
                    "vas_value",
                    models.PositiveSmallIntegerField(verbose_name="VAS 값(0~10)"),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="기록 시각"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vas_records",
                        to="core.trainingsession",
                        verbose_name="세션",
                    ),
                ),
            ],
            options={
                "verbose_name": "VAS 기록",
                "verbose_name_plural": "VAS 기록",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "phase"), name="uniq_session_phase"
                    )
                ],
            },
        ),
    ]
